version: '3'

services:
  app:
    image: php:8.1-fpm
    container_name: app
    volumes:
      - .:/var/www/html
    ports:
      - "9000"
    networks:
      - network
    depends_on:
      - db
      - redis
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=news_aggregator
      - DB_USERNAME=user
      - DB_PASSWORD=pass
      - REDIS_HOST=redis

  db:
    image: mysql:5.7
    container_name: db
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - network
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=news_aggregator
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass

  redis:
    image: redis:latest
    container_name: redis
    networks:
      - network

  react:
    container_name: news-aggregator-frontend
    build:
      context: ./../news-aggregator-frontend
      dockerfile: Dockerfile
    volumes:
      - ./../news-aggregator-frontend:/app
    ports:
      - "3000:3000"

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8000:80"
    depends_on:
      - app
    networks:
      - network

networks:
  network:

volumes:
  mysql-data: