version: '3'

services:
  app:
    image: php:8.2-fpm
    container_name: laravel-app
    volumes:
      - .:/var/www/html
    ports:
      - "8000:9000"
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - laravel-network
    depends_on:
      - db
      - redis
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=news_aggregator
      - DB_USERNAME=user
      - DB_PASSWORD=pass
      - REDIS_HOST=redis

  db:
    image: mysql:5.7
    container_name: laravel-db
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - laravel-network
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=news_aggregator
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass

  redis:
    image: redis:latest
    container_name: laravel-redis
    ports:
      - "6379:6379"
    networks:
      - laravel-network

  react:
    container_name: news-aggregator-frontend
    build:
      context: ./../news-aggregator-frontend
      dockerfile: Dockerfile
    volumes:
      - ./../news-aggregator-frontend:/app
    ports:
      - "3000:3000"
    depends_on:
      - app

networks:
  laravel-network:

volumes:
  mysql-data: